-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 01:13:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_108502523
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_108502523
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_108502523` DEFAULT CHARACTER SET utf8 ;
USE `db_108502523` ;

-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_gender` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_member` (
  `member_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `phone` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `salt` CHAR(64) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(64) NULL,
  `date_of_birth` DATE NULL,
  `gender_id` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_gender_id_idx` (`gender_id` ASC) VISIBLE,
  CONSTRAINT `fk_member__gender_id`
    FOREIGN KEY (`gender_id`)
    REFERENCES `db_108502523`.`tbl_gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_proposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_proposal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `content` TEXT NULL,
  `amount` INT NOT NULL DEFAULT 0,
  `goal` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `viewed_num` INT NOT NULL DEFAULT 0,
  `create_date` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `due_date` DATE NULL,
  `pass_date` DATE NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deactivated` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_proposal__category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_108502523`.`tbl_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_proposal_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_proposal_option` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `proposal_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proposal_id_idx` (`proposal_id` ASC) VISIBLE,
  CONSTRAINT `fk_proposal_option__proposal_id`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_108502523`.`tbl_proposal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_faq` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `proposal_id` INT UNSIGNED NOT NULL,
  `last_editor_id` INT UNSIGNED NULL,
  `question` VARCHAR(255) NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_proposal_id_idx` (`proposal_id` ASC) VISIBLE,
  INDEX `fk_last_editor_id_idx` (`last_editor_id` ASC) VISIBLE,
  CONSTRAINT `fk_faq__proposal_id`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_108502523`.`tbl_proposal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_faq__last_editor_id`
    FOREIGN KEY (`last_editor_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `proposal_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NULL,
  `user_comment` VARCHAR(255) NOT NULL,
  `proposer_response` VARCHAR(255) NULL,
  `comment_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `response_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proposal_id_idx` (`proposal_id` ASC) VISIBLE,
  INDEX `fk_member_id_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment__proposal_id`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_108502523`.`tbl_proposal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment__member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_sponsor_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_sponsor_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `member_id` INT UNSIGNED NULL,
  `proposal_option_id` INT UNSIGNED NOT NULL,
  `amount` INT NOT NULL,
  `sponsor_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_member_id_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_proposal_option_id_idx` (`proposal_option_id` ASC) VISIBLE,
  CONSTRAINT `fk_sponsor_record__member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sponsor_record__proposal_option_id`
    FOREIGN KEY (`proposal_option_id`)
    REFERENCES `db_108502523`.`tbl_proposal_option` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_proposal_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_proposal_member` (
  `proposal_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`proposal_id`, `member_id`),
  INDEX `fk_member_id_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_proposal_member__proposal_id`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_108502523`.`tbl_proposal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_proposal_member__member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_following_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_following_record` (
  `proposal_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`proposal_id`, `member_id`),
  INDEX `fk_member_id_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_following_record__proposal_id`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `db_108502523`.`tbl_proposal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_following_record__member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_login_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_login_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `member_id` INT UNSIGNED NOT NULL,
  `login_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_member_id_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_login_record__member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_member_credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_member_credential` (
  `hashed_user_id` INT UNSIGNED NOT NULL,
  `hashed_pwd_string` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`hashed_user_id`),
  CONSTRAINT `fk_member_credential__hashed_user_id`
    FOREIGN KEY (`hashed_user_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108502523`.`tbl_following_proposer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_108502523`.`tbl_following_proposer` (
  `proposer_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`proposer_id`, `member_id`),
  INDEX `fk_member_id_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_following_proposer__proposer_id`
    FOREIGN KEY (`proposer_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_following_proposer__member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `db_108502523`.`tbl_member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
